# Generated by Django 5.0.4 on 2024-07-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_demonhunter_necromancer_shadowbladeassassin_timemage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mage',
            old_name='spellbook',
            new_name='spellbook_type',
        ),
    ]
