# Generated by Django 5.0.4 on 2024-07-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_match_date_played_alter_match_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='lacation',
            new_name='location',
        ),
    ]
